server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      profile: native
      server:
        git:
          uri: https://github.com/machnikovsky/cinemania-config-server.git
          default-label: master